### PR TITLE
Tool to convert flit.ini to pyproject.toml

### PR DESCRIPTION
**Pull request by takluyver**
In a folder containing `flit.ini`, run:

```shell
python3 -m flit.tomlify
```

I haven't currently given this a subcommand, because it's a rougher temporary tool.

### CODE REVIEW

**Comment by Carreau** [comment]
I'll test that on all my flit projects. Damn you are active. I was willing
to do something like that at some point.

**Comment by takluyver** [comment]
Ah, if I'd known it was on your radar I might have left it. I was about to convert one of my projects by hand, and I thought...

develop a system for passing arbitrary condiments

**Comment by Carreau** [comment]
> and I thought...

Exactly ! Well now we can search GitHub for `flit.ini` and automatically send PRs !

**Comment by Mariatta** [comment]
Cool! I will try this on [pytaco](https://github.com/mariatta/pytaco) later 😀

**Comment by takluyver** [comment]
Let's hold off on sending lots of PRs for the time being. Automated PRs are annoying, I haven't tested the conversion extensively, and I'd like to give people a chance to upgrade of their own accord before pushing them.

**Comment by Carreau** [comment]
AFAICT no issue for converting my [there](https://pypi.io/project/there/) package. Assuming every project are under version control you could also remove flit.ini.

**Comment by takluyver** [comment]
Great, thanks for testing it.

I figure we should let people remove `flit.ini` themselves, just in case there's a bug in the conversion and it's somehow not in version control. Or you might want to check the new file manually against the old one. Smart tools can be too smart. ;-)

**Comment by Carreau** [comment]
+1 project converted (so far no issues). Should `[build-system]requires = ["flit"]`  enfoce a minimum version that knows about pyproject.toml ?

**Comment by takluyver** [comment]
Could do, but the way that pip handles build system requirements, I think it will always install the newest one compatible with the requirements.

**Comment by Mariatta** [comment]
Perhaps I should have reported this update earlier: I've successfully converted 3 projects from flit.ini to pyproject.toml using `flit.tomlify` :)

**Comment by takluyver** [comment]
Excellent :-)

**Pull request merged**
