### PR TITLE
Subcommands 'flit build' and 'flit publish'

### PR DESCRIPTION
**Pull request by takluyver**
These allow producing and uploading both wheels and sdists at the same time.

- [x] I still want to think about the naming.
- [x] Add a way to skip one format, maybe something like `flit upload --no wheel`? Should it be positive or negative?

### CODE REVIEW

**Comment by Carreau** [comment]
I think that for "simplicity" you may want to not allow to upload only one format. If you want users can fallback to twine, and upload file individually.

**Comment by takluyver** [comment]
That's true. But I'm thinking that I may at some point deprecate `flit wheel` in favour of `flit build`,  in which case you'd need a way to build just a wheel (for the no-VCS case), and then it's easy to use similar syntax to upload just a wheel.

**Comment by takluyver** [comment]
Suggested alternative names (from discussion on #108) .

Build:
- `flit build`
- `flit package`

Upload:
- `flit upload`
- `flit push`

**Comment by takluyver** [comment]
I'm sticking with `flit build`, but I've changed the other to `flit publish`.

Both commands also take `--format wheel` or `--format sdist`. The parameter can be specified multiple times, so `--format wheel --format sdist` explicitly builds both. Of course, the default if you don't specify either is to build both.

**Pull request merged**
