### PR TITLE
Allow underscore for Python 2 identifiers

### PR DESCRIPTION
**Pull request by onurguzel**
I have added the missing underscore character in the regular expressing for Python 2 `isidentifier()` check.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! Sorry I didn't say anything sooner - I was almost completely offline for Christmas.

**Comment by onurguzel** [comment]
> Thanks! Sorry I didn't say anything sooner - I was almost completely offline for Christmas.

That's fine. Actually, I am sorry, I completely forgot about the holiday season. Now, I am waiting for a new release. :) Happy New Year!

**Comment by Eric-Arellano** [comment]
Thanks, @onurguzel for the fix and @takluyver for this great tool! 

Do you know when you're planning to release this fix? I'm trying to create a Flake8 plugin and this issue is interfering with us because we need to support Python 2 for a little longer. A patch release would be appreciated when you have the time.

Thanks again for making Python packaging a better experience :)

**Comment by takluyver** [comment]
Flit 2.2 is out with this fix (among other changes)

**Pull request merged**
