### PR TITLE
Better error message for missing docstring and version.

### PR DESCRIPTION
**Pull request by Carreau**
Did that roughly in the bart. 

Was not remembering how to print Error message only cleanly.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, that looks reasonable. Can you add the same try/except for install as well, since that also gets the version number?

Also, btw, you can `sys.exit("message")` to print a message and exit with code 1.

**Comment by Carreau** [comment]
done.

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
Congratulations on getting your own [contributor graph](https://github.com/takluyver/flit/graphs/contributors)

**Pull request merged**
