### PR TITLE
Allow reading project version from source control

### PR DESCRIPTION
**Pull request by webknjaz**
I've promptly integrated setuptools_scm with flit to achieve the ability to keep a version in Git tag.

This is going to be used in python/core-workflow#286

### CODE REVIEW

**Comment by webknjaz** [comment]
Odd, build in my Travis CI account succeeded: https://travis-ci.com/webknjaz/flit/jobs/141478861.
Could you please try rerunning job for 3.4?

**Comment by webknjaz** [comment]
@takluyver ^^^

**Comment by webknjaz** [comment]
Nvmnd, triggered it myself. Ready for review.

**Comment by takluyver** [comment]
I'm glad that you're interested in flit, and I appreciate that you've spent time and effort on this change. However, I'm not going to merge it.

Flit is not designed to support all the different ways people might want to do packaging; it's meant to make it easy and clear to do packaging in one way. That way includes setting the version number in `__version__` inside the module. We often work on the assumption that more options is automatically better, but that's not what I aim for with Flit: it keeps things simple by having one way to do things.

One thing that came out of my work on Flit was a build system interface, defined in PEPs 518 and 517. This is meant to make it more practical for different package building tools to work with tools like pip. So if you want to create a tool that gets the version number from a VCS, it should be more feasible now than it was in the past. (If you do this, please name it so that it's clear it's not part of flit.)

**Comment by webknjaz** [comment]
What about having some hook for plugin in a custom method for version identification? How do change just one part without having to support full fork of flit?
In setuptools there's entry point hooks, for example, which allow other dists to register custom implementations of certain things.

**Comment by takluyver** [comment]
Sorry, at the moment I have no plans for a plugin system, for basically the same reason.

**Pull request closed without merging**
