### PR TITLE
Start testing on 3.5

### PR DESCRIPTION
**Pull request by Carreau**
--- 

It failed locally, let see what travis says.

### CODE REVIEW

**Comment by takluyver** [comment]
It looks like py.test isn't 3.5 compatible yet.

**Comment by Carreau** [comment]
Yep, GVR reported the bug upstream: https://bitbucket.org/pytest-dev/pytest/issue/744/pytest-assert-rewriting-broken-with-python

**Comment by Carreau** [comment]
Fix in progress. 
https://bitbucket.org/pytest-dev/pytest/pull-request/296/astcall-signature-changed-on-35/diff

**Comment by Carreau** [comment]
Should directly actually test on 3.5 now that it's out. 
Need to wait for py.test to make a release though.

**Comment by takluyver** [comment]
Yep, I'm subscribed to the bug where people are... bugging them about it.

How are things back in Berkeley?

**Comment by Carreau** [comment]
> How are things back in Berkeley?

Quiet, really quiet. I miss annoying you by rolling my chair back a fez **feets**. 
Haven't seen even Fernando in a while. 

But loads of things to do. Hope to have you back soon ;-P

**Comment by takluyver** [comment]
It's pretty quiet round here too, but not unpleasantly so :-)

I'll be back properly in another couple of weeks. The unread count on my IPython folder is up to 482 now. I wonder if it will hit a thousand before I mark them as read.

BTW, 'feet' is already plural - one foot, two feet. Both for the things you stand on, and the archaic measure of distance. This was brought to you by English Pedantry, inc.

**Comment by Carreau** [comment]
> The unread count on my IPython folder is up to 482 now

Will make efforts to make more issues and useless comments. 

> This was brought to you by English Pedantry, inc.

Appreciated. Stop raising your voice at end of sentences.

**Comment by takluyver** [comment]
> Appreciated. Stop raising your voice at end of sentences. 

Even when they're questions?

**Comment by Carreau** [comment]
> Even when they're questions?

You should be more confident in yourself and stop asking them.

**Pull request closed without merging**
