### PR TITLE
Normalise permission bits to 755 or 644

### PR DESCRIPTION
**Pull request by takluyver**
Apparently, the only permission bit git tracks is executable or not. So this flattens the permission bits to 755 for executable files, or 644 for non-executable, matching the default umask on Debian systems.

I still want to think about this:
- Does wheel installation preserve any more permission bits? If not,
  this is definitely fine.
- Do other version control systems store more permissions?
- Is there a reason you might want other permissions on files installed
  from wheels, e.g. to make a file not world readable? It seems redundant
  when packages come from a public index, but maybe for privately
  installed packages it makes sense.

### CODE REVIEW

**Comment by Carreau** [comment]
> Apparently, the only permission bit git tracks is executable or not

What about other versioning system. I though you didn't want to special case git in flit ?

**Comment by takluyver** [comment]
I don't. That's why it's on my list of things to check. ;-)

**Comment by brettcannon** [comment]
I just checked Mercurial and Subversion and both don't track more than execution.

**Comment by takluyver** [comment]
Thanks Brett for investigating that. With that and the existence of `distutils644`, which I heard about recently, I think this is the right thing to do.

**Pull request merged**
