### PR TITLE
Add environ FLIT_INSTALL_PYTHON

### LINKED ISSUE #294: Config to let flit install default to active virtual environment
Use case: I install only one copy of `flit` (user-wide), and use it for all projects I work on. But even if I activate the environment, `flit install` would prefer the Python it’s installed under over the environment the shell is currently in. My current “workaround” is to use `flit install --python=python`, but that seems quite redundant (and I sometimes forget it with frustrating results).

Proposed solution: Let Flit detect the `VIRTUAL_ENV` environment variable in `find_python_executable`, and use it to choose the executable if avaiable. This is backwards-incompatible, and would need to be behind a config (environ?). So maybe something like…

```py
def _find_default_python_executable():
    if not os.environ.get('FLIT_INSTALL_USE_VIRTUALENV'):
        return sys.executable
    prefix = os.environ.get("VIRTUAL_ENV')
    if not prefix:
        return sys.executable
    if sys.platform == 'win32':
        binpath = os.path.join(prefix, 'Scripts', 'python.exe')
    else:
        binpath = os.path.join(prefix, 'bin', 'python')
    if os.path.isfile(binpath):
        return binpath
    return sys.executable

def find_python_executable(python):
    if not python:
        return _find_default_python_executable()
    ...  # unchanged
```

### PR DESCRIPTION
**Pull request by uranusjr**
Close #294.

What should I supply to `.. versionadded::` in the documentation?

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks. Let's call it 2.1, as this is a new feature.

I'd mention in the docs that it can be either an absolute path, or a command name which will be found in PATH.

**Comment by uranusjr** [comment]
Documentation section extended. I also added a cross-ref in the `--python` option part.

**Comment by takluyver** [comment]
Thanks!

**Comment by Ricyteach** [comment]
It took me quite a while to figure out that I can just supply "python" as the env variable value to have flit install to the current virtual environment. I feel this capability could be made much more clear in the docs.

Can the docs be updated to be a little bit clearer about what "command name" means? Perhaps by adding this specific "FLIT_INSTALL_PYTHON = python" example, since it's probably a use case that will come up fairly often?

**Pull request merged**
